In [1]:
import pandas as pd 
import re

In [2]:
#Load data 
df_bac = pd.read_excel('res-bac-2022.xlsx')

In [3]:
#Extract first names
list_firstnames = []
for i in range (len(df_bac)) : 
    s = re.search('([^\s]+)',df_bac['Nom'][i])
    list_firstnames.append(s.group(0))

In [4]:
list_firstnames[:5]

["Sid'Ahmed", 'Aichetou', 'Tahia', 'Abdaty', 'Mohamed']

In [5]:
#Add list_firstnames to df 
df_bac['prenom'] = list_firstnames

In [6]:
df_bac.head(2)

,Num Bac,Nom,Lieu Naiss,Date Naiss,Nom Ar,Lieu Ar,Type Candidature,SERIE,Moy Bac,decision,Motif,Noreg,Wilaya,Wilaya Ar,Centre,Centre Ar,Etablissement,Etablissement AR,prenom
0,1,Sid'Ahmed Mevtah M'Bareck,Néma,2002-03-10,سيد احمد مفتاح امبارك,النعمة,CL,SN,4.185484,Ajourné,NaN,1,Hod Charghi,الحوض الشرقي,College Nema 1,إعدادية النعمه 1,College Nema 1,إعدادية النعمه 1,Sid'Ahmed
1,2,Aichetou Mohamed Mohamed Abdallahi,Néma,1996-12-01,عيشة محمد محمد عبد الله,النعمة,CL,SN,4.096774,Ajourné,NaN,1,Hod Charghi,الحوض الشرقي,College Nema 1,إعدادية النعمه 1,College Nema 1,إعدادية النعمه 1,Aichetou

In [7]:
#function to preprocess names 
def preprocess(df):
    # Step 1: Lowercase
    df['prenom'] = df['prenom'].str.lower()

    # Step 2: Split individual characters
    df['prenom'] = [list(prenom) for prenom in df['prenom']]


    # Step 3: Pad names with spaces to make all names same length
    name_length = 50
    df['prenom'] = [
        (prenom + [' ']*name_length)[:name_length] 
        for prenom in df['prenom']
    ]

    # Step 4: Encode Characters to Numbers
    df['prenom'] = [
        [
            max(0.0, ord(char)-96.0) 
            for char in prenom
        ]
        for prenom in df['prenom']
    ]
    
    
    return df

In [8]:
preprocess(df_bac)

,Num Bac,Nom,Lieu Naiss,Date Naiss,Nom Ar,Lieu Ar,Type Candidature,SERIE,Moy Bac,decision,Motif,Noreg,Wilaya,Wilaya Ar,Centre,Centre Ar,Etablissement,Etablissement AR,prenom
0,1,Sid'Ahmed Mevtah M'Bareck,Néma,2002-03-10,سيد احمد مفتاح امبارك,النعمة,CL,SN,4.185484,Ajourné,NaN,1,Hod Charghi,الحوض الشرقي,College Nema 1,إعدادية النعمه 1,College Nema 1,إعدادية النعمه 1,"[19.0, 9.0, 4.0, 0.0, 1.0, 8.0, 13.0, 5.0, 4.0..."
1,2,Aichetou Mohamed Mohamed Abdallahi,Néma,1996-12-01,عيشة محمد محمد عبد الله,النعمة,CL,SN,4.096774,Ajourné,NaN,1,Hod Charghi,الحوض الشرقي,College Nema 1,إعدادية النعمه 1,College Nema 1,إعدادية النعمه 1,"[1.0, 9.0, 3.0, 8.0, 5.0, 20.0, 15.0, 21.0, 0...."
2,3,Tahia Khatari Abd El Wahab,Bougadoum,1997-07-26,تحي خطاري عبد الوهاب,بوكادوم,CL,SN,3.483871,Ajourné,NaN,1,Hod Charghi,الحوض الشرقي,College Nema 1,إعدادية النعمه 1,College Nema 1,إعدادية النعمه 1,"[20.0, 1.0, 8.0, 9.0, 1.0, 0.0, 0.0, 0.0, 0.0,..."
3,4,Abdaty Itawel Oumrou Ahmedou,Basseknou,2000-08-04,عبداتي اطول عمر احمدو,باسكنو,CL,SN,8.914062,Sessionnaire,NaN,1,Hod Charghi,الحوض الشرقي,Lycée Bassiknou,ثانوية باسكنو,Lycée Bassiknou,ثانوية باسكنو,"[1.0, 2.0, 4.0, 1.0, 20.0, 25.0, 0.0, 0.0, 0.0..."
4,5,Mohamed Salem Mohamed El Heiba Taleb Khyar,Néma,1996-02-26,محمد سالم محمد الهيب الطالب اخيار,النعمة,CL,SN,3.963710,Ajourné,NaN,1,Hod Charghi,الحوض الشرقي,College Nema 1,إعدادية النعمه 1,College Nema 1,إعدادية النعمه 1,"[13.0, 15.0, 8.0, 1.0, 13.0, 5.0, 4.0, 0.0, 0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47246,55758,F'Eitoumatt Abdarahmane Abdarahmane,Soudoud,2000-01-24,افيطمات عبد الرحمن عبد الرحمن,السدود,CL,SN,6.751344,Ajourné,NaN,13,Nouakchott 1 (Nord),انواكشوط الشمالية,Ecole Ibnou Rouchd Teyaret,مدرسة ابن رشد نيارت,Ecole Ibnou Rouchd Teyaret,مدرسة ابن رشد نيارت,"[6.0, 0.0, 5.0, 9.0, 20.0, 15.0, 21.0, 13.0, 1..."
47247,55759,Salem Brahim Abdellahi,Sebkha,1995-02-12,السالمه ابراهيم عبدالله,السبخة,CL,LO,4.129032,Ajourné,NaN,13,Nouakchott 1 (Nord),انواكشوط الشمالية,Ecole Zahra Dar Naim,مدرسة الزهراء - دار النعيم,Ecole Zahra Dar Naim,مدرسة الزهراء - دار النعيم,"[19.0, 1.0, 12.0, 5.0, 13.0, 0.0, 0.0, 0.0, 0...."
47248,55760,Fetya Sidi Mohamed Bebe,Dar Naim,2000-04-01,فتية سيد محمد ببه,دار النعيم,CL,LO,4.548387,Ajourné,NaN,13,Nouakchott 1 (Nord),انواكشوط الشمالية,Ecole Zahra Dar Naim,مدرسة الزهراء - دار النعيم,Ecole Zahra Dar Naim,مدرسة الزهراء - دار النعيم,"[6.0, 5.0, 20.0, 25.0, 1.0, 0.0, 0.0, 0.0, 0.0..."
47249,55761,Oum Kelthoum El Hadj Rawane Fall,Tevragh Zeina,2004-11-04,امكلثوم الحاج روان,تفرغ زينه,CL,SN,4.076613,Ajourné,NaN,14,Nouakchott 2 (Ouest),انواكشوط الغربية,Ecole Normale des Instituteurs,مدرسة تكوين المعلمين,Ecole Normale des Instituteurs,مدرسة تكوين المعلمين,"[15.0, 21.0, 13.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0...."
47250,55762,Bamba Sidi Haibe Eghervel,Teyaret,2003-10-15,بمب سيد هيب أغرفل,تيارت,CL,SN,2.258065,Ajourné,NaN,13,Nouakchott 1 (Nord),انواكشوط الشمالية,Lycée Toujounine 1,ثانوية توجنين 1,Lycée Toujounine 1,ثانوية توجنين 1,"[2.0, 1.0, 13.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0,..."

In [9]:
from tensorflow.keras.models import load_model
import numpy as np

In [10]:
# Predictions
pred_model = load_model('MouF_final2.h5')

result = pred_model.predict(np.asarray(
    df_bac['prenom'].values.tolist())).squeeze(axis=1)

df_bac['M ou F?'] = [
    'M' if logit > 0.5 else 'F' for logit in result
]

df_bac['Probabilité'] = [
    logit if logit > 0.5 else 1.0 - logit for logit in result
]


df_bac['Probabilité'] = df_bac['Probabilité'].round(2)
df_bac = df_bac.drop(['prenom'], axis = 1)

1477/1477 [==============================] - 68s 46ms/step

In [11]:
df_bac[['Nom','M ou F?','Probabilité']].head(30)

                                           Nom M ou F?  Probabilité
0                    Sid'Ahmed Mevtah M'Bareck       M         1.00
1           Aichetou Mohamed Mohamed Abdallahi       F         1.00
2                   Tahia Khatari Abd El Wahab       F         1.00
3                 Abdaty Itawel Oumrou Ahmedou       M         1.00
4   Mohamed Salem Mohamed El Heiba Taleb Khyar       M         1.00
5           Nana Moulaye Abdallah Moulay Smail       F         0.96
6                        Neziha Ahmedou Sadevi       F         1.00
7                 El Moustapha Mohamed Echekar       M         0.80
8           Khadijetou El Houssein El Houssein       F         1.00
9                 Hainna Naji Sid El Moustaphe       F         0.97
10             Dedda Mohamed Salem Abderrazagh       F         0.51
11                Lala Ahmed Nouh Sidi Mohamed       F         1.00
12                   Baba Mohamed El Agheb Ely       M         0.78
13            Souadou El Haiba Cheickh El Avia       F         1.00
14    Vatimetou Zahra El Haiba Cheickh El Avia       F         1.00
15                        Abdellahi Ali Khouya       M         1.00
16    Mohamed Mohamed Lemine M'Bareck El Kheir       M         1.00
17                      Chama Abdellahi Moussa       F         0.99
18                           Sidi Cheikhna Tar       M         1.00
19          Cheikh Mohamed Laghdaf Ahmed Beida       M         0.99
20                            Mohamed Eyda Dah       M         1.00
21                          Fatma Hamady Jelad       F         1.00
22              Balaty Cheikhna Mohamed Jimane       M         0.89
23                   Sidaty Chrif Ahmed Mouadh       M         1.00
24          Khaled Cheikh Taleb Bouye El Veteh       M         0.99
25      El Khayt Sidi Mohamed Ahmed El Mokhtar       M         0.80
26                    Selma Mohmed Salem Eydah       F         1.00
27                     Mohamed Sid'Amar Tvaeil       M         1.00
28                     Racky Cheibani Doukouré       F         0.99
29                         Alassane Hamady Dia       M         1.00